- t: MySQL
  s: '### MySQL

    MySQL adalah sebuah perangkat lunak sistem manajemen basis data SQL (bahasa Inggris:
    database management system) atau DBMS yang multialur, multipengguna, dengan sekitar
    6 juta instalasi di seluruh dunia. MySQL AB membuat MySQL tersedia sebagai perangkat
    lunak gratis di bawah lisensi GNU General Public License (GPL), tetapi mereka
    juga menjual di bawah lisensi komersial untuk kasus-kasus di mana penggunaannya
    tidak cocok dengan penggunaan GPL.'
  d: '2026-05-11'
- t: SQL
  s: '### SQL

    SQL (  S-Q-L,  "sequel"; Structured Query Language) adalah sebuah bahasa yang
    digunakan untuk mengakses data dalam basis data relasional. Bahasa ini secara
    de facto merupakan bahasa standar yang digunakan dalam manajemen basis data relasional.
    Saat ini hampir semua server basis data yang ada mendukung bahasa ini untuk melakukan
    manajemen datanya.'
  d: '2026-05-11'
- t: Microsoft SQL Server
  s: '### Microsoft SQL Server

    Microsoft SQL Server adalah sebuah sistem manajemen basis data relasional (RDBMS)
    produk Microsoft. Bahasa kueri utamanya adalah Transact-SQL yang merupakan implementasi
    dari SQL standar ANSI/ISO yang digunakan oleh Microsoft dan Sybase. Umumnya SQL
    Server digunakan di dunia bisnis yang memiliki basis data berskala kecil sampai
    dengan menengah, tetapi kemudian berkembang dengan digunakannya SQL Server pada
    basis data besar.'
  d: '2026-05-11'
- t: Maktabah Syamilah
  s: '### 📘 Knowledge: Maktabah Syamilah


    Maktabah Syamilah (المكتبة الشاملة; Maktaba Shamela) merupakan sebuah peranti
    lunak komputer gratis berbasis Microsoft Windows yang berbentuk Pembaca (reader)
    buku elektronik dan perpustakaan digital. Peranti ini dapat dimasukkan dengan
    berkas (file) buku elektronik hingga puluhan ribu kitab. Peranti ini memiliki
    berbagai fitur seperti pencarian cepat, pencatatan, referensi silang, portabel-itas
    dan berbagai kemudahan lainnya yang tidak didapat pada kitab berwujud fisik biasa.
    Selain versi PC, juga tersedia versi mobile untuk platform Android dan iPhone
    yang dapat didownload dari situs penerbitnya....


    _Source: Wikipedia_'
  d: '2026-05-11'
- t: PostgreSQL
  s: '### 📘 Knowledge: PostgreSQL


    PostgreSQL (  POHST-gres-kew-EL), atau dikenal juga dengan Postgres, adalah sebuah
    sistem basis data relasional yang menonjolkan ekstensabilitas dan kesesuaian dengan
    SQL. PostgreSQL menggunakan transaksi dengan properti atomisitas (atomicity),
    konsistensi (consistency), isolasi (isolation), dan daya tahan (durability) atau
    sering disebut ACID. PostgreSQL mendukung sebagian besar sistem operasi utama
    seperti Windows, Linux, MacOS, FreeBSD, dan OpenBSD. Selain itu, juga mendukung
    berbagai bidang kerja mulai dari penerapan pada mesin tunggal, gudang data (data
    warehouse), hingga data lake....


    _Source: Wikipedia_'
  d: '2026-05-11'
- t: Oracle Corporation
  s: '### 📘 Knowledge: Oracle Corporation


    Oracle Corporation adalah sebuah perusahaan teknologi komputer multinasional yang
    berkantor pusat di Austin, Texas. Perusahaan ini menjual perangkat lunak dan teknologi
    basis data, sistem komputasi awan, dan perangkat lunak perusahaan—terutama sistem
    manajemen basis data buatannya sendiri. Perusahaan ini sebelumnya berkantor pusat
    di Redwood Shores, California, hingga Desember 2020 saat memindahkan kantor pusatnya
    ke Texas. Pada tahun 2020, Oracle merupakan perusahaan perangkat lunak dengan
    pendapatan dan kapitalisasi pasar terbesar kedua di dunia. Perusahan ini juga
    mengembangkan dan membangun alat untuk pengembangan dan sistem basis data dari
    perangkat lunak kelas menengah, perangkat lunak perencanaan sumber daya perusahaan,
    perangkat lunak manajemen sumber daya manusia, perangkat lunak ...


    _Source: Wikipedia_'
  d: '2026-05-11'
- t: MongoDB
  s: '### 📘 Knowledge: MongoDB


    MongoDB (dari humongous) adalah sistem basis data berorentasi dokumen lintas platform.
    Diklasifikasikan sebagai basis data NoSQL, MongoDB menghindari struktur basis
    data relasional tabel berbasis tradisional yang mendukung JSON seperti dokumen
    dengan skema dinamis (MongoDB menyebutnya sebagai format BSON), membuat integrasi
    data dalam beberapa jenis aplikasi lebih mudah dan lebih cepat. Dirilis di bawah
    Server Side Public License, MongoDB adalah perangkat lunak bebas dan sumber terbuka....


    _Source: Wikipedia_'
  d: '2026-05-11'
- t: Graph database
  s: '### 📘 Knowledge: Graph database


    Graph database (Basis data graf) dalam dunia ilmu komputer adalah basis data yang
    menggunakan struktur data graf yg memiliki komponen simpel (node), tepi (edge)
    dan atribut (properties) untuk merepresentasikan penyimpanan data. Basis data
    graf menyediaakan index-free adjacency, konsep yang memungkinkan penyimpanan dan
    Pemrosesan graf secara efisien. Dalam sistem ini, setiap simpul langsung terhubung
    dengan simpul-simpul yang ada di sekitarnya tanpa perlu menggunakan indeks tambahan
    untuk mencari simpul-simpul tersebut. Artinya, hubungan antar simpul disimpan
    langsung di dalam simpul itu sendiri, sehingga akses ke simpul terrait bisa dilakukan
    secara cepas tanpa pencarían melalui indeks yang terpisah. Pendekatan ini sangat
    berguna dalam aplikasi yang membutuhkan performa tinggi, seperti rek...


    _Source: Wikipedia_'
  d: '2026-05-11'
- t: Firebase
  s: '### 📘 Knowledge: Firebase


    Firebase adalah suatu layanan dari Google yang digunakan untuk mempermudah para
    pengembang aplikasi dalam mengembangkan aplikasi. Dengan adanya Firebase, pengembang
    aplikasi bisa fokus mengembangkan aplikasi tanpa harus memberikan usaha yang besar.
    Dua fitur yang menarik dari Firebase yaitu Firebase Remote Config dan Firebase
    Realtime Database. Selain itu terdapat fitur pendukung untuk aplikasi yang membutuhkan
    pemberitahuan yaitu Firebase Notification....


    _Source: Wikipedia_'
  d: '2026-05-11'
- t: SQLite
  s: '### 📘 Knowledge: SQLite


    SQLite merupakan sebuah sistem manajemen basisdata relasional yang bersifat ACID-compliant
    dan memiliki ukuran pustaka kode yang relatif kecil, ditulis dalam bahasa C. SQLite
    merupakan proyek yang bersifat public domain yang dikerjakan oleh D. Richard Hipp....


    _Source: Wikipedia_'
  d: '2026-05-11'
- t: MariaDB
  s: '### 📘 Knowledge: MariaDB


    MariaDB merupakan versi pengembangan terbuka dan mandiri dari MySQL. Sejak diakuisisinya
    MySQL oleh Oracle pada September 2010, Monty Program sebagai penulis awal kode
    sumber MySQL memisahkan diri dari pengembangan dan membuat versi yang lebih mandiri
    yakni MariaDB....


    _Source: Wikipedia_'
  d: '2026-05-11'
- t: Google Cloud Platform
  s: '### 📘 Knowledge: Google Cloud Platform


    Google Cloud Platform, (atau GCP) adalah kumpulan layanan komputasi awan yang
    ditawarkan oleh Google. GCP berjalan di atas infrastruktur yang sama yang digunakan
    oleh Google untuk produk internalnya, seperti Google Search, YouTube dan Gmail.
    Bersamaan dengan seperangkat alat manajemen, GCP menyediakan serangkaian layanan
    cloud modular termasuk komputasi, penyimpanan data, Analisis data dan pembelajaran
    mesin..Registrasi membutuhkan detail kartu kredit atau rekening bank....


    _Source: Wikipedia_'
  d: '2026-05-12'
